package modelo;

public enum Evento {
    CAMBIO_FICHAS_JUGADOR,
    INICIAR_JUEGO,
    ACTUALIZAR_TABLERO,
    PASAR_TURNO,
    CAMBIO_RONDA,
    CIERRE_JUEGO,
    JUGADOR_DESCONECTADO,
    CARGAR_PARTIDA,
    FIN_DEL_JUEGO
}
